# Generated by Django 5.0 on 2024-01-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.DeleteModel(
            name='AppointmentService',
        ),
    ]
