# Generated by Django 5.0 on 2024-01-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_appointment_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('MedCert', 'Medical Certificate (Med Cert)'), ('Dental', 'Dental Appointment'), ('Physical', 'Physical Examination'), ('Counseling', 'Counseling Session'), ('Specialist', 'Specialist Consultation'), ('FollowUp', 'Follow-up Appointment')], max_length=50),
        ),
    ]
